services:
  # Streamlit Container
  container_streamlit:
    #build: .
    #image: streamlit_yt:test_version
    image: unclad3610/ytb_dl_streamlit:latest
    container_name: ytb_dl_streamlit
    environment:
      - AUDIO_PATH=./storage/audio/
      - VIDEO_PATH=./storage/video/
      - AVAILABLE_KEYS=User:f165f-az6516A1*d5az16d5a1f65 # Create your own key here
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    ports:
      - "8501:8030"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://container_streamlit:8030"]
      interval: 30s
      timeout: 10s
      retries: 3