# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: uv run pytest
        language: python
        types: [python]
        pass_filenames: false
