# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix]

  # - repo: https://github.com/kootenpv/gittyleaks
  #   rev: v1.3.0
  #   hooks:
  #     - id: gittyleaks

  # - repo: local
  #   hooks:
  #     - id: run-pytest
  #       name: Run Pytest
  #       entry: uv run pytest
  #       language: python
  #       types: [python]
  #       pass_filenames: false
