# Name of the workflow 
name: Upload Docker images

# Trigger
on:
  pull_request:
    branches: ["main"]

# Jobs
jobs:
  # Job - Push Streamlit image
  push_streamlit_image:
    name: Push Streamlit image
    runs-on: ubuntu-latest

    # Actions to execute
    steps:
      # Used to clone the repository in the runner
      - uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Get version from .env file
      - name: Load .env file
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .github/workflows/.env

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build & Push Docker Image
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: unclad3610/ytb_dl_streamlit:${{ env.streamlit_version }}, unclad3610/ytb_dl_streamlit:latest